fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.2.1"
    vcsrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
      ref: "1.0.1"
  symlinks:
    githosting: "#{source_dir}"

