name 'tohuwabohu-githosting'
version '1.0.0'
source 'https://github.com/tohuwabohu/tohuwabohu-githosting.git'
project_page 'https://github.com/tohuwabohu/tohuwabohu-githosting'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Manage hosting of git repositories.'
description ''

dependency 'example42/puppi', '2.x'
dependency 'puppetlabs/stdlib', '4.x'
